#!/usr/bin/env ansible-playbook

- hosts: all
  become: yes
  gather_facts: yes
  vars:
    users: 1
    slaves: 1
    cidr: "172.18.1.1/20"

  tasks:
    - name: Baseline Machine
      yum: name={{ item }} state=present
      with_items:
        - docker
        - python-docker-py
      tags:
        - baseline

    - name: Start Docker Engine
      service: name=docker state=started
      tags:
        - baseline

    - name: Backup existing SSH config
      command: cp /etc/ssh/ssh_config /etc/ssh/ssh_config_backup
      tags:
        - ssh
        - backup_ssh
        - baseline

    - name: Create group ansiblelab
      group:
           name=ansiblelab
           state=present
      tags:
        - group
        - baseline

    - name: Create users with loop
      user:
          name={{ item }}
          password={{ item | password_hash('sha512') }}
          home=/home/{{ item }}
          createhome=yes
          group=ansiblelab
          generate_ssh_key=yes
          state=present
      with_sequence: start=1 end={{ users }} format=ansiblelabuser%d
      tags:
        - users
        - baseline

    - name: unlock sshd_config
      command: chattr -i /etc/ssh/sshd_config
      changed_when: yes
      tags:
        - ssh
        - users
        - baseline

    - name: insert ansible in sshd allowedusers
      replace:
        dest: /etc/ssh/sshd_config
        regexp: '^(AllowUsers(?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_sequence: start=1 end={{ users }} format=ansiblelabuser%d
      tags:
        - ssh
        - users
        - baseline

    - name: lock sshd_config
      command: chattr +i /etc/ssh/sshd_config
      changed_when: yes
      tags:
        - ssh
        - users
        - baseline

    - name: Create Docker network for ansiblelab
      command: docker network create -d bridge --internal --subnet={{ cidr }} ansiblelab_nw
      tags:
        - docker_network

    - name: Build Master and Slave Images (Module)
      docker_image:
        path: "{{ item }}"
        dockerfile: Dockerfile
        state: present
        name: ansible_lab/{{ item }}
        tag: latest
      with_items:
        - master
        - slave
      tags:
        - m_startup
        - m_build_images

    - name: Build Master and Slave Images (CLI)
      command: docker build -t ansible_lab/{{ item }}:latest {{ item }}
      with_items:
        - master
        - slave
      tags:
        - cli_startup
        - cli_build_images

    - include: ansible_lab_master_slave.yml
      with_sequence: start=1 end={{ users }}
      loop_control:
        loop_var: master_name

    - name: Service discovery
      command: utilities/service_discovery.sh {{ users }} {{ slaves }}
      tags:
        - m_startup
        - cli_startup

    - name: Remove ansiblelab users
      user:
        name={{ item }}
        state=absent
        force=yes
        remove=yes
      with_sequence: start=1 end={{ users }} format=ansiblelabuser%d
      tags:
        - remove_users
        - remove_baseline

    - name: Remove ansiblelab group
      group:
        name=ansiblelab
        state=absent
      tags:
        - remove_group
        - remove_baseline
